#!/bin/bash
TESTS=$(find txrest/tests -maxdepth 1 -name 'test_*.py')
coverage run $(which trial) $TESTS || exit $?
coverage report --include='txrest/*' --omit='txrest/tests/*'
coverage html -d txrest/tests/reports --include='txrest/*' --omit='txrest/tests/*'
